XASMFLAGS =

SRC = rd16.S \
      rd32.S \
      rd8.S \
      rd32_x16.S \
      rd_regs.S \
      restore_regs.S \
      save_regs.S \
      wr16.S \
      wr32.S \
      wr8.S \

include ../mk/library.mk

